version: 1.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
shallow_clone: true
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: '&nuget restore'
build_script:
- ps: "&msbuild -p:Configuration=$($env:CONFIGURATION) CPubLib\\CPubLib.csproj"
- ps: "&msbuild -p:Configuration=$($env:CONFIGURATION) CPubLib.Test\\CPubLib.Test.csproj"
- ps: "&msbuild -p:Configuration=$($env:CONFIGURATION) CPubLib.Test\\CPubLib.Test.csproj"
- ps: "$targetRids = @('win-x64', 'win-arm64', 'osx-x64', 'linux-x64', 'linux-arm64')"
- ps: "$targetRids | foreach { &dotnet publish CPubMake\\CPubMake.csproj -c $($env:CONFIGURATION) -f net5.0 -r $_ --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true; Compress-Archive -Path CPubMake\\bin\\Release\\net5.0\\$_\\publish\\* -DestinationPath CPubMake\\bin\\Release\\net5.0\\CPubMake-v$($env:APPVEYOR_BUILD_VERSION)-$_.zip }"
test:
  assemblies:
    only:
    - '**\*.Test.dll'
artifacts:
- path: '**\*.nupkg'
- path: '**\CPubMake*.zip'
deploy:
- provider: NuGet
  api_key:
    secure: bR/0Cw2eRUeBiW/ZtJ2yNui38HoUM7kPDhN3POQFdYaE9kH2b+ZCppX+MG8b0xn3
  skip_symbols: true
  artifact: /.*\.nupkg/
- provider: GitHub
  tag: CPubMake-v$(APPVEYOR_BUILD_VERSION)
  description: '$(APPVEYOR_REPO_COMMIT_MESSAGE)'
  auth_token:
    secure: NMn/VM+fZ3Xzj7CTJLJYh0G7+TzIVrRHQ4IHJnCnxojN45gbkDRDk+3h0r3/SG0I
  artifact: /.*\.zip/
  draft: false
  prerelease: false