version: 1.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
shallow_clone: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: '&nuget restore'
build:
  verbosity: minimal
on_success:
  - ps: "&dotnet publish CPubMake\\CPubMake.csproj -c Release -f net5.0 -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true"
test:
  assemblies:
    only:
    - '**\*.Test.dll'
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: bR/0Cw2eRUeBiW/ZtJ2yNui38HoUM7kPDhN3POQFdYaE9kH2b+ZCppX+MG8b0xn3
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master