//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPubLib.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPubLib.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;container version=&quot;1.0&quot; xmlns=&quot;urn:oasis:names:tc:opendocument:xmlns:container&quot;&gt;
        ///  &lt;rootfiles&gt;
        ///    &lt;rootfile full-path=&quot;OEBPS/content.opf&quot; media-type=&quot;application/oebps-package+xml&quot;/&gt;
        ///  &lt;/rootfiles&gt;
        ///&lt;/container&gt;.
        /// </summary>
        internal static string EpubContainerContent {
            get {
                return ResourceManager.GetString("EpubContainerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEBPS/content.opf.
        /// </summary>
        internal static string EpubContentEntryName {
            get {
                return ResourceManager.GetString("EpubContentEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEBPS/.
        /// </summary>
        internal static string EpubContentRoot {
            get {
                return ResourceManager.GetString("EpubContentRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEBPS/nav.xhtml.
        /// </summary>
        internal static string EpubNavEntryName {
            get {
                return ResourceManager.GetString("EpubNavEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html, body, div {
        ///    width: 100%;
        ///    height: 100%;
        ///    margin: 0;
        ///}
        ///
        ///div {
        ///    display: flex;
        ///    justify-content: center;
        ///    align-items: center;
        ///}
        ///
        ///img {
        ///    width: 100%;
        ///    height: 100%;
        ///    object-fit: contain;
        ///}.
        /// </summary>
        internal static string EpubPageCSS {
            get {
                return ResourceManager.GetString("EpubPageCSS", resourceCulture);
            }
        }
    }
}
