//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPubLib.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPubLib.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;container version=&quot;1.0&quot; xmlns=&quot;urn:oasis:names:tc:opendocument:xmlns:container&quot;&gt;
        ///  &lt;rootfiles&gt;
        ///    &lt;rootfile full-path=&quot;OEBPS/content.opf&quot; media-type=&quot;application/oebps-package+xml&quot;/&gt;
        ///  &lt;/rootfiles&gt;
        ///&lt;/container&gt;.
        /// </summary>
        internal static string EpubContainerContent {
            get {
                return ResourceManager.GetString("EpubContainerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEBPS/content.opf.
        /// </summary>
        internal static string EpubContentEntryName {
            get {
                return ResourceManager.GetString("EpubContentEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEBPS/.
        /// </summary>
        internal static string EpubContentRoot {
            get {
                return ResourceManager.GetString("EpubContentRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEBPS/nav.xhtml.
        /// </summary>
        internal static string EpubNavEntryName {
            get {
                return ResourceManager.GetString("EpubNavEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;html lang=&quot;en-US&quot; xml:lang=&quot;en-US&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width={1}, height={2}&quot; /&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;svg width=&quot;{1}&quot; height=&quot;{2}&quot; viewBox=&quot;0 0 {1} {2}&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xml:space=&quot;preserve&quot;&gt;
        ///        &lt;image x=&quot;{5}&quot; y=&quot;0&quot; width=&quot;{3}&quot; height=&quot;{4}&quot; xlink:href=&quot;{0}&quot;/&gt;
        ///    &lt;/svg&gt;
        ///  &lt;/body&gt;
        ///&lt;/html [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EpubPageTemplate {
            get {
                return ResourceManager.GetString("EpubPageTemplate", resourceCulture);
            }
        }
    }
}
